sudo: required
services:
  - docker

before_install:
  - docker build -t mahlatsisambe/Docker-React -f Dockerfile.dev .

script:
  - docker run  mahlatsisambe/Docker-React npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-30647383899" #Search S3
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
